# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tafunc 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "tafunc"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["YAMAMOTO, Masayuki"]
  s.date = "2013-12-12"
  s.description = "Useful methods are added to TaLib, TaLib::Function, and TaLib::TAFunc."
  s.email = "martin.route66.blues+github@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/tafunc.rb",
    "test/helper.rb",
    "test/test_tafunc.rb"
  ]
  s.homepage = "http://github.com/mephistobooks/tafunc"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.9"
  s.summary = "TAFunc: another talib_ruby wrapper and extensions"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_development_dependency(%q<talib_ruby>, [">= 1.0.5"])
      s.add_development_dependency(%q<activesupport>, [">= 4.0.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<talib_ruby>, [">= 1.0.5"])
      s.add_dependency(%q<activesupport>, [">= 4.0.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<talib_ruby>, [">= 1.0.5"])
    s.add_dependency(%q<activesupport>, [">= 4.0.0"])
  end
end

